---

jobs:
- name: ship-it
  serial: true
  public: true
  plan:
  - aggregate:
    - get: docker-alpine-m2
      trigger: true
    - get: docker-alpine-boot
      trigger: true
    trigger: true
  - put: version
    params: {bump: minor}
  - put: release-image
    params:
      build: docker-alpine-boot
      tag_as_latest: true
      tag: version/number
  - put: docker-alpine-m2 
    params: 
      only_tag: true
      repository: docker-alpine-m2
      tag: version/number

resources:
    
- name: docker-alpine-m2
  type: docker-image
  source:
    repository: sbodiu/m2

- name: docker-alpine-boot
  type: git
  source:
    uri: git@github.com:sergiubodiu/docker-alpine-boot.git
    branch: master
    private_key: {{private-key-github-concourse}}
    paths: Dockerfile

- name: release-image
  type: docker-image
  source:
    repository: sbodiu/boot
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:sergiubodiu/version-concourse.git
    branch: master
    file: docker-alpine-boot/version
    private_key: {{private-key-github-concourse}}
    git_user: "Sergiu sbodiu@pivotal.io"

